CSHARP-2295: Deprecate group command helpers
ksadoff/mongo-csharp-driver pull request #2
Opened 2019-06-06 15:21 UTC by ksadoff

https://jira.mongodb.org/browse/CSHARP-2295

2019-06-06 15:22 UTC, ksadoff commented
Ready for interim review

2019-06-06 19:39 UTC, vincentkam requested changes
PR #2! 😸 A good portion of the comments I made in https://github.com/ksadoff/mongo-csharp-driver/pull/1 should also apply here

2019-06-06 19:41 UTC, ksadoff commented
https://evergreen.mongodb.com/version/5cf9302f2fbabe336e1e86eb

2019-06-11 17:53 UTC, vincentkam requested changes
Getting close! 
@rstam Thoughts on updating `Feature.GroupCommand`'s `supportRemovedVersion`? I defined it as 4.0.0 rc1 in [CSHARP-2285](https://jira.mongodb.org/browse/CSHARP-2285), which is likely the first time we noticed when the server stopped responding to the command. The [driver ticket](https://jira.mongodb.org/browse/DRIVERS-370) states it was finally removed in 4.1.1. I see no harm in continuing to test it on the versions of the server that do support the group command, and the deprecation notices that Katie added correctly state that the `group` command was deprecated in server version 3.4.

2019-06-11 17:53 UTC, vincentkam commented on tests/MongoDB.Driver.Legacy.Tests/MongoCollectionTests.cs
> +#pragma warning disable 618
This works! We tend use wrap only the deprecated method call with the `#pragma` statements though, like so: 
```
#pragma warning disable 618
                        Assert.Throws<MongoExecutionTimeoutException>(() => _collection.Group(args));
#pragma warning restore
```

This wasn't in our dev/style guide, so I've updated the guide to indicate this :)

2019-06-11 17:53 UTC, vincentkam commented on tests/MongoDB.Driver.Legacy.Tests/MongoCollectionTests.cs
> +
Super minor nit: there's some extraneous whitespace before and after the `#pragma` statements in this file that could be removed :)

2019-06-11 19:53 UTC, rstam approved these changes

2019-06-11 21:31 UTC, vincentkam commented
@ksadoff : After a quick offline discussion with @rstam, we think it shouldn't hurt to update `Feature.GroupCommand`'s `supportRemovedVersion` to 4.1.1 as suggested by the Drivers ticket :)

2019-06-12 20:10 UTC, vincentkam requested changes
Almost there! 😄

2019-06-12 20:10 UTC, vincentkam commented on src/MongoDB.Driver.Core/Core/Misc/Feature.cs
> +        private static readonly Feature __groupCommand = new Feature("GroupCommand", new SemanticVersion(1, 0, 0), new SemanticVersion(4, 1, 1, "rc1"));
Sorry, I was unclear here!  We don't know the pre-release version where the command was removed so for now let's assume it was removed in 4.1.1 with a pre-release string of `""`, which effectively says "any pre release version of 4.1.1" (see [here ](https://github.com/mongodb/mongo-csharp-driver/blob/21aff044981244cf1158c6d8e01e6bf542a3ed17/src/MongoDB.Driver.Core/Core/Misc/SemanticVersion.cs#L107)for all the gory details).

2019-06-13 20:45 UTC, vincentkam approved these changes
LGTM 😄

2019-06-13 20:47 UTC, ksadoff commented
Ready for final review

2019-06-14 17:19 UTC, DmitryLukyanov approved these changes
LGTM

2019-06-19 19:46 UTC, ksadoff commented
Rebased, merged, and pushed.

2019-06-19 19:46 UTC, closed without merging